### ISSUE TITLE
Component available on NPM

### ISSUE THREAD

**Issue by kyro38** [lfades/static-tweet#24]
Hi, thanks for your work ! :) 

I found that someone made a npm package of you component : https://github.com/transitive-bullshit/react-static-tweets 

You could maybe update the read me 👍

**Comment by lfades** [comment]
I was not interested on sharing it as a package back then because its usage didn't feel like I wanted it to be, I wanted to be able to just import `<Tweet id="1" />` and have it working, nothing else, one line and it's good to go.

I managed to do that in [Rauch's blog](https://github.com/rauchg/blog), but it was done with a hack similar to what Apollo does for pre-rendering (ugly stuff), so even though it was it, it had multiple deal breakers for me.

Now that RSC are closer to release, and Next.js is using them, I'll be working again in static-tweet and eventually get to what I want!

I also have a refactor pending to the core of how the tweets are being processed as it currently has some unexpected limitations.

For the moment I'll close the issue, I had some goals for the project that were not possible until now 😌
